export const UI_STRINGS = {
  APP_TITLE: 'DevProduct Manager',
  BUTTONS: {
    CREATE: 'Create',
    FULL_SCREEN: 'Full Screen',
    BULK_CREATE: 'Bulk Create',
    ADD_ROW: 'Add Row',
    REMOVE_ROW: 'Remove',
    IMPORT_JSON: 'Import JSON',
    EXPORT_JSON: 'Export JSON',
    DOWNLOAD_TEMPLATE: 'Download Template',
    CREATE_ALL: 'Create All',
    CLEAR_ALL: 'Clear All',
    LOAD_DRAFT: 'Load Draft',
    CLEAR_DRAFT: 'Clear Draft',
    BULK_OPERATIONS: 'Bulk Operations',
    SELECT_ALL: 'Select All',
    CLEAR_SELECTION: 'Clear Selection',
  },
  STATUS: {
    LOADING: 'Loading...',
    IDLE: 'Navigate to a Roblox experience page to load products',
    CREATING: 'Creating products...',
    VALIDATING: 'Validating...',
  },
  ERRORS: {
    PRODUCT_NOT_FOUND: 'Product not found',
    UPDATE_PRICE_FAILED: 'Failed to update price',
    UPDATE_NAME_FAILED: 'Failed to update name',
    INVALID_JSON: 'Invalid JSON format',
    EMPTY_PRODUCTS: 'Please add at least one product',
    VALIDATION_FAILED: 'Please fix validation errors before submitting',
    DUPLICATE_NAMES: 'Duplicate product names detected',
  },
  EMPTY_STATES: {
    NO_PRODUCTS: 'No products found.',
    NO_RESULTS: 'No products match your search.',
    NO_BULK_PRODUCTS: 'Add products using the "Add Row" button or import a JSON file.',
  },
  TOOLTIPS: {
    CREATE_PRODUCT: 'Create New Product',
    FULL_SCREEN: 'Open in full screen',
    BULK_CREATE: 'Create multiple products at once',
    ADD_ROW: 'Add a new product row',
    REMOVE_ROW: 'Remove this product',
    IMPORT_JSON: 'Import products from JSON file',
    EXPORT_JSON: 'Export products to JSON file',
  },
  MESSAGES: {
    BULK_CREATE_SUCCESS: '{count} product(s) created successfully',
    BULK_CREATE_PARTIAL: '{successful} created, {failed} failed',
    DRAFT_LOADED: 'Draft loaded with {count} product(s)',
    DRAFT_CLEARED: 'Draft cleared',
    CONFIRM_CLEAR_ALL: 'Are you sure you want to clear all products?',
    CONFIRM_CLEAR_DRAFT: 'Are you sure you want to clear the saved draft?',
  },
  VALIDATION: {
    NAME_REQUIRED: 'Product name is required',
    NAME_MIN_LENGTH: 'Name must be at least 3 characters',
    NAME_MAX_LENGTH: 'Name must not exceed 50 characters',
    PRICE_REQUIRED: 'Price is required',
    PRICE_INVALID: 'Price must be a valid number',
    PRICE_NEGATIVE: 'Price cannot be negative',
    PRICE_MAX: 'Price cannot exceed 1,000,000,000 Robux',
  },
} as const;

